{{- if .Values.backend.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cloudops-sre-platform.fullname" . }}-backend-migrate
  labels:
    {{- include "cloudops-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.backend.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "cloudops-sre-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend-migration
    spec:
      restartPolicy: Never
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            - alembic
            - upgrade
            - head
          env:
            - name: APP_ENV
              value: {{ .Values.backend.env.appEnv | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.backend.env.corsOrigins | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.backend.env.logLevel | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.backend.env.logFormat | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudops-sre-platform.databaseSecretName" . }}
                  key: {{ .Values.backend.database.secretKey }}
          resources:
            {{- toYaml .Values.backend.migrations.resources | nindent 12 }}
{{- end }}
