apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudops-sre-platform.fullname" . }}-backend-config
  labels:
    {{- include "cloudops-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  APP_ENV: {{ .Values.backend.env.appEnv | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.corsOrigins | quote }}
  LOG_LEVEL: {{ .Values.backend.env.logLevel | quote }}
  LOG_FORMAT: {{ .Values.backend.env.logFormat | quote }}
