{{- if .Values.backend.database.externalSecret.enabled }}
apiVersion: {{ .Values.backend.database.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "cloudops-sre-platform.fullname" . }}-database
  labels:
    {{- include "cloudops-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: {{ .Values.backend.database.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "backend.database.externalSecret.secretStoreRef.name is required when externalSecret.enabled=true" .Values.backend.database.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.backend.database.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "cloudops-sre-platform.databaseSecretName" . }}
    creationPolicy: {{ .Values.backend.database.externalSecret.targetCreationPolicy | quote }}
  data:
    - secretKey: {{ .Values.backend.database.secretKey | quote }}
      remoteRef:
        key: {{ required "backend.database.externalSecret.remoteSecretName is required when externalSecret.enabled=true" .Values.backend.database.externalSecret.remoteSecretName | quote }}
        property: {{ .Values.backend.database.externalSecret.remoteProperty | quote }}
{{- end }}
