apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudops-sre-platform.fullname" . }}-frontend
  labels:
    {{- include "cloudops-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudops-sre-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "cloudops-sre-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
